# Electivos backend #


## Host
@localhost=http://localhost:10000

### set host
@host = {{localhost}}

##var

###end var
### GET Carreras disponibles en la bd
GET {{host}}/ucn/carreras

### GET Electivos disponibles en la bd
GET {{host}}/ucn/electivos

### SEND EMAIL 
GET {{host}}/ucn/email

### POST formulario request
POST {{host}}/ucn/formulario
Content-Type: application/json

{
  "Rut": "19.100.657-7",
  "Nombre": "Dionisio Alejandro Olivares Astudillo",
  "Correo": "",
  "Carrera": "ICCI",
  "Cantidad": 3,
  "Electivo1": "Redes 1",
  "Electivo2": "Redes 2",
  "Electivo3": "Redes 3"
}

### POST rut validator 
POST {{host}}/ucn/rut                  
Content-Type: application/json

{
  "Rut": "19.239.494-1"
}

### POST correo validator 
POST {{host}}/ucn/correo                  
Content-Type: application/json

{
  "Correo": "xxx@ucgn.cl"
}



### 
GET {{host}}/ucn/solicitud



### POST correo validator 
POST {{host}}/ucn/AprobarPostulacion                  
Content-Type: application/json

{
  "rut_alumno": "201676061",
  "nombre_electivo":"E1"
}