# Electivos backend #


## Host
@localhost=http://localhost:10000
@domain=http://ucn.electivos.backend/
### set host
@host = {{localhost}}

##var

###end var
### GET Carreras disponibles en la bd
GET {{host}}/ucn/carreras

### GET Electivos disponibles en la bd
GET {{host}}/ucn/electivos

### SEND EMAIL 
GET {{host}}/ucn/email

### POST formulario request
POST {{host}}/ucn/formulario
Content-Type: application/json

{
  "Rut": "19.100.657-7",
  "Nombre": "Dionisio Alejandro Olivares Astudillo",
  "Correo": "",
  "Carrera": "ICCI",
  "Cantidad": 3,
  "Electivo1": "Redes 1",
  "Electivo2": "Redes 2",
  "Electivo3": "Redes 3"
}

### POST rut validator 
POST {{host}}/ucn/rut                  
Content-Type: application/json

{
  "Rut": "19.239.494-1"
}

### POST correo validator 
POST {{domain}}/ucn/correo                  
Content-Type: application/json

{
  "Correo": "xxx@ucgn.cl"
}



### 
GET {{host}}/ucn/solicitudes



### POST correo validator 
POST {{host}}/ucn/AprobarPostulacion                  
Content-Type: application/json

{
  "rut_alumno": "19.239.594-1",
  "nombre_electivo":"E2"
}


### GET registro electivos en un semestre
GET {{host}}/ucn/Dashboard?semestre=2021-1            


### GET informe curricular alumno
GET {{host}}/ucn/InformeCurricular?rut=20.167.605-1


### GET informe curricular alumno
GET {{host}}/ucn/TablaInformeCurricular?rut=20.236.276-1

### GET informe curricular alumno
GET {{host}}/ucn/semestres